### PR TITLE
Testing PR (for actions)

### PR DESCRIPTION
**Pull request by Moosems**

### CODE REVIEW

**Comment by oehhar** [comment]
Hi Moosens,
thank you for the pull request. I have no idea what a "asdf" in an md file does. Can you explain, what this does ?

Thanks and take care,
Harald

**Comment by fvogelnew1** [comment]
The title of this PR looks like a test.

**Comment by oehhar** [comment]
Thanks, Francois, I appreciate.
Take care,
Harald

**Comment by auriocus** [comment]
Moosems cloned the repo and noted, that the Github Actions does not work in his repo, it failed on Windows. By submitting a pull request with (non-significant) change he could trigger the Github Actions in this repository, which showed that also here it does not work any longer. The reason is that Github updated the latest Windows to 2022. I fixed the problem with the most recent commit (you can see that the Actions have built everything again)

**Comment by Moosems** [comment]
Yes, I was attempting to test the CI actions (this was a test PR) and decided to instead make a test repo.

**Comment by oehhar** [comment]
Thank you, I appreciate !
Take care,
Harald

**Pull request closed without merging**
